Repository docker/app, pull requests merged in 2018-08, with the labels that each got.

#330 Fix typo in `maitainers`.
  e2e/commands_test.go
  e2e/testdata/init-singlefile.dockerapp
  examples/hello-world/README.md
  examples/hello-world/hello-world.dockerapp
  examples/voting-app/voting-app.dockerapp/metadata.yml
  internal/packager/init.go
  internal/packager/init_test.go
Labels: status/2-code-review

#323 Some more `helm` package refactoring
  internal/helm/helm.go
  internal/helm/templateconversion/convert.go
  internal/helm/templateloader/interpolate.go
  internal/helm/templateloader/loader.go
  internal/helm/templateloader/volume.go
  internal/helm/templatetypes/types.go
  internal/helm/templatev1beta2/stack.go
  internal/templatetypes/types.go
  internal/validator/validate.go
Labels: status/2-code-review

#324 Use `docker/cli` Transform function…
  Gopkg.lock
  internal/helm/templateloader/loader.go
  vendor/github.com/docker/cli/cli/command/service/ps.go
  vendor/github.com/docker/cli/cli/command/stack/deploy.go
  vendor/github.com/docker/cli/cli/command/utils.go
  vendor/github.com/docker/cli/cli/compose/loader/loader.go
  vendor/github.com/docker/cli/cli/config/config.go
  vendor/github.com/docker/cli/opts/opts.go
Labels: status/2-code-review

#328 Use docker/cli template.ExtractVariables instead of own impl.
  Gopkg.lock
  internal/helm/helm.go
  internal/packager/init.go
  internal/packager/init_test.go
  vendor/github.com/docker/cli/cli/compose/template/template.go
Labels: status/2-code-review

#334 e2e: Fix exit code on failure.
  e2e/main_test.go
Labels: status/0-triage

#335 Fix helm generation
  Gopkg.lock
  e2e/commands_test.go
  internal/helm/helm.go
  internal/packager/init.go
  internal/render/render.go
  vendor/github.com/docker/cli/cli/command/stack/cmd.go
  vendor/github.com/docker/cli/cli/compose/template/template.go
Labels: status/2-code-review

#246 Check that Compose file version is supported during init
  internal/packager/init.go
  internal/packager/init_test.go
Labels: status/2-code-review

#292 Implement `docker-app fork`
  .gitignore
  README.md
  cmd/docker-app/fork.go
  cmd/docker-app/root.go
  e2e/commands_test.go
  e2e/fork/simple.dockerapp/docker-compose.yml
  e2e/fork/simple.dockerapp/metadata.yml
  e2e/fork/simple.dockerapp/settings.yml
  e2e/testdata/expected-fork-metadata-no-rename.golden
  e2e/testdata/expected-fork-metadata.golden
  internal/packager/fork.go
  internal/packager/fork_test.go
  internal/packager/init.go
  internal/packager/init_test.go
  internal/packager/registry.go
  internal/packager/registry_test.go
  internal/types/metadata.go
  specification/schemas/metadata_schema_v0.1.json
Labels: status/1-design-review

#340 Heavy docker-app loading refactoring
  cmd/docker-app/deploy.go
  cmd/docker-app/helm.go
  cmd/docker-app/image-add.go
  cmd/docker-app/image-load.go
  cmd/docker-app/inspect.go
  cmd/docker-app/merge.go
  cmd/docker-app/push.go
  cmd/docker-app/render.go
  cmd/docker-app/save.go
  cmd/docker-app/split.go
  cmd/docker-app/validate.go
  e2e/commands_test.go
  internal/compose/compose.go
  internal/helm/helm.go
  internal/image/image.go
  internal/inspect/inspect.go
  internal/inspect/inspect_test.go
  internal/inspect/testdata/inspect-full.golden
  internal/inspect/testdata/inspect-no-description.golden
  internal/inspect/testdata/inspect-no-maintainers.golden
  internal/inspect/testdata/inspect-no-settings.golden
  internal/packager/extract.go
  internal/packager/fork.go
  internal/packager/fork_test.go
  internal/packager/init.go
  internal/packager/init_test.go
  internal/packager/packing.go
  internal/packager/registry.go
  internal/packager/split.go
  internal/settings/load.go
  internal/settings/load_test.go
  internal/types/types.go
  internal/validator/validate.go
  internal/validator/validate_test.go
  lib/lib.go
  loader/loader.go
  loader/loader_test.go
  render/render.go
  render/render_test.go
  types/init.go
  types/init_test.go
  types/metadata/metadata.go
  types/metadata/metadata_test.go
  types/types.go
  types/types_test.go
Labels: status/2-code-review

#346 Make docker/app not exposed to yaml bomb
  Gopkg.lock
  Gopkg.toml
  cmd/docker-app/render.go
  e2e/render_test.go
  internal/helm/helm.go
  internal/inspect/inspect.go
  internal/packager/fork.go
  internal/packager/init.go
  internal/packager/registry.go
  internal/renderer/yatee/driver.go
  internal/settings/load.go
  internal/settings/settings.go
  internal/yaml/yaml.go
  internal/yaml/yaml_test.go
  internal/yatee/samples/main.go
  internal/yatee/yatee.go
  internal/yatee/yatee_test.go
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/yaml.go
Labels: status/2-code-review

#345 Fix "required variable" error message 👼
  render/render.go
Labels: status/2-code-review

#343 Send reg auth
  cmd/docker-app/deploy.go
Labels: status/1-design-review

#349 Capitalise help outputs
  README.md
  cmd/docker-app/deploy.go
  cmd/docker-app/push.go
  cmd/docker-app/root.go
  cmd/docker-app/save.go
Labels: status/2-code-review

#352 Fix `docker-app save` on single-file application
  e2e/commands_test.go
  internal/packager/registry.go
  types/types.go
Labels: status/2-code-review

#353 Update README for v0.4.1 release
  README.md
Labels: status/0-triage

#354 Tidying some tests
  e2e/commands_test.go
  e2e/example_test.go
  internal/packager/init_test.go
  types/metadata/metadata_test.go
Labels: status/2-code-review

#361 Fix panic when using `x-enabled: false` instead of a string
  render/render.go
  render/render_test.go
Labels: status/2-code-review

#365 gradle: Pin version as current latest image is broken.
  Dockerfile.gradle
Labels: status/0-triage

#356 Add support for loading URLs.
  e2e/commands_test.go
  e2e/testdata/helloworld-inspect.golden
  internal/packager/extract.go
  loader/loader.go
Labels: status/2-code-review

#364 Fix more case for `x-enabled` parsing failures
  render/render.go
  render/render_test.go
Labels: status/2-code-review

#362 Fix the application name when extracting a docker image
  internal/packager/extract.go
  internal/packager/extract_test.go
Labels: status/2-code-review

#368 e2e: Expose Container struct and Assert* functions.
  e2e/commands_test.go
  e2e/helper.go
  e2e/helper_test.go
Labels: status/0-triage

#366 Expose settings functions externally
  cmd/docker-app/validate.go
  internal/helm/helm.go
  internal/inspect/inspect.go
  internal/inspect/inspect_test.go
  internal/packager/init.go
  internal/packager/registry.go
  internal/packager/split.go
  internal/validator/validate.go
  internal/validator/validate_test.go
  loader/loader_test.go
  render/render.go
  render/render_test.go
  types/metadata/load.go
  types/metadata/load_test.go
  types/metadata/metadata.go
  types/settings/load.go
  types/settings/load_test.go
  types/settings/merge.go
  types/settings/merge_test.go
  types/settings/opts.go
  types/settings/settings.go
  types/settings/settings_test.go
  types/types.go
  types/types_test.go
Labels: status/2-code-review
