Repository docker/app, pull requests merged in 2018-07, with the labels that each got.

#260 Extract: clean path, mainly to remove eventual trailing separator.
  internal/packager/extract.go
Labels: status/2-code-review

#266 Update README with Windows limitation
  README.md
  examples/wordpress/README.md
Labels: status/3-docs-review

#268 Fix YAML document separator
  e2e/testdata/init-singlefile.dockerapp
  examples/hello-world/hello-world.dockerapp
  internal/packager/extract.go
  internal/packager/split.go
Labels: status/2-code-review

#263 Add docs for --stack-version flag of helm subcommand
  README.md
  cmd/docker-app/helm.go
Labels: status/3-docs-review

#267 Fix Helm E2E tests
  e2e/binary_test.go
  e2e/helm.chart/Chart.yaml
  e2e/helm.chart/templates/stack.yaml
  e2e/helm.chart/values.yaml
  e2e/testdata/helm-expected.chart/values.yaml
Labels: status/2-code-review

#270 Follow-up on missing separators in README.md(s)
  README.md
  examples/hello-world/README.md
Labels: status/2-code-review

#271 Remove "Automatically validating …" part of the README…
  README.md
Labels: status/3-docs-review

#272 Remove Exclude from gometalinter 🐸
  gometalinter.json
Labels: status/2-code-review

#273 Remove `renderer` package dependency from `image` package
  cmd/docker-app/image-add.go
  internal/image/image.go
Labels: status/2-code-review

#275 Add tests to `renderer.Inspect`
  e2e/binary_test.go
  internal/renderer/inspect.go
  internal/renderer/inspect_test.go
  internal/renderer/testdata/inspect-full.golden
  internal/renderer/testdata/inspect-no-description.golden
  internal/renderer/testdata/inspect-no-maintainers.golden
  internal/renderer/testdata/inspect-no-settings.golden
Labels: status/2-code-review

#276 Fix gometalinter not recursing
  Makefile
  cmd/docker-app/deploy.go
  cmd/docker-app/root.go
  e2e/container.go
  gometalinter.json
  internal/names.go
  internal/packager/packing.go
Labels: status/2-code-review

#277 Fix `docker-app` pack regression
  internal/packager/packing.go
Labels: status/2-code-review

#278 split/merge: Update short help, add to README.
  README.md
  cmd/docker-app/merge.go
Labels: status/2-code-review

#274 Some tests coverage
  .gitignore
  internal/names_test.go
  internal/types/init.go
  internal/types/init_test.go
  internal/types/metadata.go
  internal/types/metadata_test.go
Labels: status/2-code-review

#282 Fix `make -f docker.Makefile cross` doing more than it should
  docker.Makefile
Labels: status/2-code-review

#280 Extract renderers on their own package…
  Dockerfile
  Jenkinsfile
  Makefile
  cmd/docker-app/deploy.go
  cmd/docker-app/helm.go
  cmd/docker-app/image-add.go
  cmd/docker-app/inspect.go
  cmd/docker-app/render.go
  docker.Makefile
  e2e/binary_test.go
  e2e/helm.dockerapp/docker-compose.yml
  e2e/render/template-gotemplate.dockerapp/docker-compose.yml
  e2e/render/template-gotemplate.dockerapp/env.yml
  e2e/render/template-gotemplate.dockerapp/expected.txt
  e2e/render/template-gotemplate.dockerapp/metadata.yml
  e2e/render/template-gotemplate.dockerapp/settings-0.yml
  e2e/render/template-gotemplate.dockerapp/settings.yml
  e2e/render_test.go
  e2e/testdata/helm-expected.chart/templates/stack-v1beta1.yaml
  internal/render/helm.go
  internal/render/inspect.go
  internal/render/inspect_test.go
  internal/render/render.go
  internal/render/render_test.go
  internal/render/testdata/inspect-full.golden
  internal/render/testdata/inspect-no-description.golden
  internal/render/testdata/inspect-no-maintainers.golden
  internal/render/testdata/inspect-no-settings.golden
  internal/renderer/driver/driver.go
  internal/renderer/gotemplate/doc.go
  internal/renderer/gotemplate/driver.go
  internal/renderer/gotemplate/driver_test.go
  internal/renderer/mustache/doc.go
  internal/renderer/mustache/driver.go
  internal/renderer/mustache/driver_test.go
  internal/renderer/renderer.go
  internal/renderer/renderer_test.go
  internal/renderer/yatee/doc.go
  internal/renderer/yatee/driver.go
  internal/renderer/yatee/driver_test.go
  internal/version.go
  vars.mk
Labels: status/2-code-review

#284 Wordpress example update
  examples/wordpress/README.md
  examples/wordpress/with-secrets.yml
Labels: status/2-code-review

#269 Add specifications
  Dockerfile
  Gopkg.lock
  Gopkg.toml
  Jenkinsfile
  Jenkinsfile.baguette
  Makefile
  cmd/yamlschema/main.go
  docker.Makefile
  e2e/commands_test.go
  e2e/container.go
  e2e/example_test.go
  e2e/helper_test.go
  e2e/list_test.go
  e2e/main_test.go
  internal/render/render.go
  specification/README.md
  specification/schemas/metadata_schema_v0.1.json
  vars.mk
  vendor/github.com/docker/cli/cli/compose/loader/example1.env
  vendor/github.com/docker/cli/cli/compose/loader/example2.env
  vendor/github.com/docker/cli/cli/compose/loader/full-example.yml
  vendor/github.com/docker/cli/cli/compose/schema/data/config_schema_v3.0.json
  vendor/github.com/docker/cli/cli/compose/schema/data/config_schema_v3.1.json
  vendor/github.com/docker/cli/cli/compose/schema/data/config_schema_v3.2.json
  vendor/github.com/docker/cli/cli/compose/schema/data/config_schema_v3.3.json
  vendor/github.com/docker/cli/cli/compose/schema/data/config_schema_v3.4.json
  vendor/github.com/docker/cli/cli/compose/schema/data/config_schema_v3.5.json
  vendor/github.com/docker/cli/cli/compose/schema/data/config_schema_v3.6.json
  vendor/github.com/docker/cli/cli/compose/schema/data/config_schema_v3.7.json
  vendor/github.com/docker/cli/cli/compose/schema/data/doc.go
  vendor/github.com/docker/cli/kubernetes/README.md
Labels: status/2-code-review

#289 Update gitignore
  .gitignore
Labels: status/2-code-review

#291 Remove `parseSettings` and use `docker/cli` code to parse key=value env
  cmd/docker-app/deploy.go
  cmd/docker-app/helm.go
  cmd/docker-app/image-add.go
  cmd/docker-app/render.go
  cmd/docker-app/root.go
Labels: status/1-design-review

#287 Remove targets from metadata…
  README.md
  e2e/commands_test.go
  e2e/helm.dockerapp/metadata.yml
  e2e/render/envvariables.dockerapp/metadata.yml
  e2e/render/template-gotemplate.dockerapp/metadata.yml
  e2e/render/template-mustache.dockerapp/metadata.yml
  e2e/testdata/init-singlefile.dockerapp
  examples/hello-world/README.md
  examples/hello-world/hello-world.dockerapp
  examples/voting-app/voting-app.dockerapp/metadata.yml
  examples/wordpress/wordpress.dockerapp/metadata.yml
  integrations/gradle/example/simple.dockerapp/metadata.yml
  internal/packager/init.go
  internal/packager/init_test.go
  internal/types/metadata.go
  specification/schemas/metadata_schema_v0.1.json
Labels: status/2-code-review

#295 Add --version flag
  cmd/docker-app/root.go
Labels: status/2-code-review

#298 Remove `ExtractWithOrigin` and refactor `Extract`
  cmd/docker-app/deploy.go
  cmd/docker-app/helm.go
  cmd/docker-app/image-add.go
  cmd/docker-app/image-load.go
  cmd/docker-app/inspect.go
  cmd/docker-app/merge.go
  cmd/docker-app/pack.go
  cmd/docker-app/render.go
  cmd/docker-app/split.go
  internal/packager/extract.go
  internal/packager/registry.go
  internal/render/render.go
Labels: status/2-code-review

#302 Initialize dockerCli
  Gopkg.lock
  cmd/docker-app/root.go
  vendor/github.com/docker/cli/cli/debug/debug.go
Labels: status/2-code-review

#305 Fix `docker-app deploy` error with ResolveImage
  cmd/docker-app/deploy.go
Labels: status/2-code-review

#306 Update installation instructions to point to 0.3.0
  README.md
Labels: status/2-code-review

#308 Add missing .PHONY on schemas target
  Makefile
  docker.Makefile
Labels: status/2-code-review

#310 Add specification/bindata.go target
  Makefile
  docker.Makefile
Labels: status/2-code-review

#311 Lint some more code
  internal/helm/helm.go
  internal/packager/extract.go
  internal/packager/init.go
  internal/packager/split.go
  internal/templateloader/interpolate.go
  internal/templateloader/loader.go
  internal/templateloader/merge.go
Labels: status/2-code-review

#301 Add a completion sub-command to generate completion for bash
  README.md
  cmd/docker-app/completion.go
  cmd/docker-app/root.go
Labels: status/2-code-review

#317 Bump docker/cli to latest master
  Gopkg.lock
  vendor/github.com/docker/cli/cli/compose/types/types.go
Labels: status/2-code-review

#318 Do not ignore error error when generating completion
  cmd/docker-app/completion.go
Labels: status/2-code-review

#322 lib: Add an accessible Render function.
  lib/lib.go
Labels: status/2-code-review

#326 Switch back to mergo upstream
  Gopkg.lock
  Gopkg.toml
Labels: status/2-code-review

#327 Validate command now returns every errors it can find
  internal/validator/validate.go
  internal/validator/validate_test.go
Labels: status/2-code-review
