Repository docker/app, pull requests merged in 2018-06, with the labels that each got.

#231 Load settings after `packager.Extract`
  cmd/docker-app/deploy.go
  cmd/docker-app/helm.go
  cmd/docker-app/image-add.go
  cmd/docker-app/render.go
Labels: status/2-code-review

#233 Fix windows make
  Makefile
  vars.mk
Labels: status/2-code-review

#236 Update README with the latest docker-app version for WGET
  README.md
Labels: status/3-docs-review

#234 Add ls command.
  Jenkinsfile
  Makefile
  cmd/docker-app/ls.go
  cmd/docker-app/root.go
  docker.Makefile
  e2e/binary_test.go
  e2e/container.go
  e2e/list_test.go
  internal/image/image.go
  internal/names.go
  internal/packager/registry.go
Labels: status/2-code-review

#232 Small cmd refactoring to use the same cli helper as docker/cli
  cmd/docker-app/deploy.go
  cmd/docker-app/image-add.go
  cmd/docker-app/inspect.go
  cmd/docker-app/main.go
  cmd/docker-app/merge.go
  cmd/docker-app/pack.go
  cmd/docker-app/render.go
  cmd/docker-app/root.go
  cmd/docker-app/save.go
  cmd/docker-app/split.go
  cmd/docker-app/version.go
  internal/packager/init.go
  internal/packager/packing.go
  internal/packager/split.go
  internal/renderer/inspect.go
Labels: status/2-code-review

#248 Factorize the 3 file names used in docker-app
  e2e/binary_test.go
  internal/names.go
  internal/packager/extract.go
  internal/packager/init.go
  internal/packager/init_test.go
  internal/packager/packing.go
  internal/packager/registry.go
  internal/packager/split.go
  internal/renderer/helm.go
  internal/renderer/inspect.go
  internal/renderer/render.go
  internal/types/metadata.go
Labels: status/2-code-review

#245 Lookup default permutation of app folder before literal name
  internal/packager/extract.go
Labels: status/2-code-review

#251 README: Update the 'usage' section.
  README.md
Labels: status/3-docs-review

#254 Remove docker prune
  Jenkinsfile.baguette
Labels: status/2-code-review

#247 Allow creating helm chart for v1beta1 spec of Compose-Kubernetes
  cmd/docker-app/helm.go
  e2e/binary_test.go
  e2e/testdata/helm-expected.chart/templates/stack-v1beta1.yaml
  e2e/testdata/invalid-stack-version.golden
  internal/renderer/helm.go
Labels: status/1-design-review

#255 examples: Remove references to pack and unpack (experimental).
  examples/wordpress/README.md
Labels: status/3-docs-review

#256 Update outdated examples (single-file, helm, etc.)
  examples/hello-world/README.md
  examples/hello-world/hello-world.dockerapp
  examples/voting-app/README.md
  examples/voting-app/voting-app.dockerapp/metadata.yml
  examples/wordpress/README.md
Labels: status/3-docs-review

#240 split, merge: Handle in-place conversion, move out of experimental.
  cmd/docker-app/merge.go
  cmd/docker-app/root.go
  cmd/docker-app/split.go
  e2e/binary_test.go
  internal/packager/extract.go
Labels: status/2-code-review
